@startuml


actor User

User -> UI ++ #application: I want to like Post
UI -> LikeController --++ #application :  POST /like/{postID}
LikeController -> LikeController #application: validate(postID)
LikeController -> LikeController #application: getUserFromSecurityContext()
LikeController -> LikeService --++ #application: addLikePost(postID, userID)
LikeService -> LikeService: verifyLike()
LikeService -> LikeRepository --++ #application: registerLike(postID, userID)
LikeRepository -> LikeService --++ #application: Optional<Like>
LikeService --> LikeController --++ #application: Optional<Like>
LikeController --> UI --++ #application: ResponseEntity 200 code!
UI --> User -- #application: Post liked!


@enduml