@startuml


actor User

User -> UI ++ #application: I want to add like to Post
UI -> PostController --++ #application : Send PostDto
PostController -> PostController #application: validate(PostDto)
PostController -> PostService --++ #application: addLikePost(PostDto)
PostService -> PostMapper --++ #application: toEntity(PostDto)
PostMapper --> PostService --++ #application: transform PostDto into Post
PostService -> Post --++ #application: registerLike(postID, userID)
Post -> Post #application: registerLike(postID, userID)
Post -> PostService --++ #application: Optional<Like>
PostService -> PostRepository --++ #application: updatePost(Post)
PostRepository -> PostRepository #application: updatePost(Post)
PostRepository --> PostService --++ #application: Optional<Post>
PostService -> PostMapper --++ #application: toDto(Post)
PostMapper --> PostService --++ #application: transform Post into PostDto
PostService --> PostController --++ #application: Optional<PostDto>
PostController --> UI --++ #application: ResponseEntity 200 code!
UI --> User -- #application: Post updated with Like!


@enduml