@startuml

actor User

User -> UI ++ #application: I want to add comment to post
UI -> CommentController ++ #application: POST /comment/{postID}
CommentController -> CommentController: validatePostExists(postID)
CommentController -> CommentController: validateCommentDto(CommentDto)
CommentController -> CommentController: getUserFromSecurityContext()
CommentController -> CommentService ++ #application: registerComment(postID, userID, CommentDto)
CommentService -> CommentMapper ++ #application: toEntity(CommentDto)
CommentMapper --> CommentService --: Comment
CommentService -> CommentRepository ++ #application: save(Comment)
CommentRepository --> CommentService --: Optional<Comment>
CommentService --> CommentController --: Optional<Comment>
CommentController --> UI --: ResponseEntity 201 code!
UI --> User --: Comment added successfully!

@enduml