@startuml


actor User

User -> UI ++ #application: I want to add like to Post
UI -> PostController --++ #application : Send PostDto
PostController -> PostController #application: validate(PostDto)
PostController -> PostService --++ #application: addLikePost(PostDto)
PostService -> PostMapper --++ #application: toEntity(PostDto)
PostMapper --> PostService --++ #application: transform PostDto into Post
PostService -> LikeRepository --++ #application: createLike(postID, userID)
LikeRepository -> LikeRepository #application: save(Like)
LikeRepository --> PostService --++ #application: Optional<Like>
PostService -> PostRepository --++ #application: updatePost(Like)
PostRepository -> PostRepository #application: updatePost(Like)
PostRepository --> PostService --++ #application: Optional<Post>
PostService --> PostController --++ #application: Optional<Post>
PostController --> UI --++ #application: ResponseEntity 200 code!
UI --> User -- #application: Post updated with Like!


@enduml