name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    permissions:
      contents: read
      checks: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Create .env file
        run: |
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=27017" >> .env
          echo "SECRET_KEY=dummy-secret" >> .env
          echo "JWT_EXPIRES_IN=3600" >> .env

      - name: Build and Test with Gradle Wrapper
        run: ./gradlew build test

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "**/build/test-results/**/*.xml"
          check_name: "Test Results"
          fail_on: nothing

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: build/libs/*.jar

  code-quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Create .env file
        run: |
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=27017" >> .env
          echo "SECRET_KEY=dummy-secret" >> .env
          echo "JWT_EXPIRES_IN=3600" >> .env

      - name: Run code quality checks
        run: ./gradlew checkstyleMain checkstyleTest pmdMain pmdTest
        continue-on-error: true

      - name: Archive code quality reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: code-quality-reports
          path: |
            **/build/reports/checkstyle/**
            **/build/reports/pmd/**

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4.0.0
